import { lazy, Suspense } from 'react';
import { BrowserRouter, Routes, Route } from 'react-router-dom';
import Navbar from './components/shared/Navbar';
import Footer from './components/shared/Footer';
import Loader from './components/shared/Loader';
import ProtectedRoute from './components/shared/ProtectedRoute';
const Home = lazy(() => import('./pages/Home'));
const Login = lazy(() => import('./pages/auth/Login'));
const Register = lazy(() => import('./pages/auth/Register'));
const ForgotPassword = lazy(() => import('./pages/auth/ForgotPassword'));
const ResetPassword = lazy(() => import('./pages/auth/ResetPassword'));
const ProductListing = lazy(() => import('./pages/products/ProductListing'));
const ProductDetail = lazy(() => import('./pages/products/ProductDetail'));
const Cart = lazy(() => import('./pages/cart/Cart'));
const Checkout = lazy(() => import('./pages/checkout/Checkout'));
const OrderSuccess = lazy(() => import('./pages/checkout/OrderSuccess'));
const Dashboard = lazy(() => import('./pages/account/Dashboard'));
const Profile = lazy(() => import('./pages/account/Profile'));
const MyOrders = lazy(() => import('./pages/account/MyOrders'));
const Wishlist = lazy(() => import('./pages/account/Wishlist'));
const Addresses = lazy(() => import('./pages/account/Addresses'));
const Reviews = lazy(() => import('./pages/account/Reviews'));
const VendorDashboard = lazy(() => import('./pages/vendor/VendorDashboard'));
const VendorProducts = lazy(() => import('./pages/vendor/VendorProducts'));
const VendorOrders = lazy(() => import('./pages/vendor/VendorOrders'));
const VendorEarnings = lazy(() => import('./pages/vendor/VendorEarnings'));
const AdminDashboard = lazy(() => import('./pages/admin/AdminDashboard'));
const AdminVendors = lazy(() => import('./pages/admin/AdminVendors'));
const AdminOrders = lazy(() => import('./pages/admin/AdminOrders'));
export default function App() { return <BrowserRouter><Navbar /><Suspense fallback={<Loader />}><Routes><Route path="/" element={<Home />} /><Route path="/products" element={<ProductListing />} /><Route path="/products/:slug" element={<ProductDetail />} /><Route path="/login" element={<Login />} /><Route path="/register" element={<Register />} /><Route path="/forgot-password" element={<ForgotPassword />} /><Route path="/reset-password/:token" element={<ResetPassword />} /><Route path="/cart" element={<ProtectedRoute roles={['customer','admin']}><Cart /></ProtectedRoute>} /><Route path="/checkout" element={<ProtectedRoute roles={['customer','admin']}><Checkout /></ProtectedRoute>} /><Route path="/order-success/:id" element={<ProtectedRoute><OrderSuccess /></ProtectedRoute>} /><Route path="/account" element={<ProtectedRoute roles={['customer','admin']}><Dashboard /></ProtectedRoute>} /><Route path="/account/profile" element={<ProtectedRoute><Profile /></ProtectedRoute>} /><Route path="/account/orders" element={<ProtectedRoute><MyOrders /></ProtectedRoute>} /><Route path="/account/wishlist" element={<ProtectedRoute><Wishlist /></ProtectedRoute>} /><Route path="/account/addresses" element={<ProtectedRoute><Addresses /></ProtectedRoute>} /><Route path="/account/reviews" element={<ProtectedRoute><Reviews /></ProtectedRoute>} /><Route path="/vendor/dashboard" element={<ProtectedRoute roles={['vendor','admin']}><VendorDashboard /></ProtectedRoute>} /><Route path="/vendor/products" element={<ProtectedRoute roles={['vendor','admin']}><VendorProducts /></ProtectedRoute>} /><Route path="/vendor/orders" element={<ProtectedRoute roles={['vendor','admin']}><VendorOrders /></ProtectedRoute>} /><Route path="/vendor/earnings" element={<ProtectedRoute roles={['vendor','admin']}><VendorEarnings /></ProtectedRoute>} /><Route path="/admin" element={<ProtectedRoute roles={['admin']}><AdminDashboard /></ProtectedRoute>} /><Route path="/admin/vendors" element={<ProtectedRoute roles={['admin']}><AdminVendors /></ProtectedRoute>} /><Route path="/admin/orders" element={<ProtectedRoute roles={['admin']}><AdminOrders /></ProtectedRoute>} /><Route path="*" element={<div className="mx-auto max-w-3xl px-4 py-24 text-center"><h1 className="font-heading text-5xl text-navy">Page Not Found</h1><a className="btn-gold mt-6 inline-block" href="/">Go Home</a></div>} /></Routes></Suspense><Footer /></BrowserRouter>; }
