import { useState } from 'react';
import { useParams } from 'react-router-dom';
import { FaHeart, FaStar } from 'react-icons/fa';
import Loader from '../../components/shared/Loader';
import SEO from '../../components/shared/SEO';
import { useGetProductQuery } from '../../store/api/productApi';
import { useAddToCartMutation, useToggleWishlistMutation } from '../../store/api/orderApi';
import { money } from '../../utils/helpers';
export default function ProductDetail() { const { slug } = useParams(); const { data, isLoading } = useGetProductQuery(slug); const [qty, setQty] = useState(1); const [tab, setTab] = useState('Description'); const [addToCart] = useAddToCartMutation(); const [wish] = useToggleWishlistMutation(); if (isLoading) return <Loader />; const p = data?.product; if (!p) return <div className="p-10 text-center">Product not found</div>; const images = p.images?.length ? p.images : [p.thumbnail || '/logo.png']; return <main className="mx-auto max-w-7xl px-4 py-10"><SEO title={`${p.name} | Niksa Mart`} /><p className="text-sm text-gray-500">Home / Products / {p.name}</p><div className="mt-6 grid gap-10 lg:grid-cols-2"><div><img src={images[0]} alt={p.name} className="h-96 w-full rounded-lg bg-gray-50 object-contain p-6" /><div className="mt-3 flex gap-3">{images.map(src => <img key={src} src={src} className="h-20 w-20 rounded border object-contain p-1" />)}</div></div><section><span className="rounded bg-navy/10 px-2 py-1 text-sm font-bold text-navy">{p.vendorId?.shopName}</span><h1 className="mt-3 font-heading text-5xl text-navy">{p.name}</h1><div className="mt-3 flex items-center gap-2 text-gold"><FaStar /> {p.rating} verified reviews ({p.totalReviews})</div><div className="mt-5 flex items-center gap-3"><span className="font-heading text-4xl text-gold">{money(p.salePrice)}</span><span className="text-gray-400 line-through">{money(p.price)}</span></div>{p.variants?.length > 0 && <select className="input mt-5 max-w-sm">{p.variants.map(v => <option key={v.name}>{v.name} - {money(v.price)}</option>)}</select>}<div className="mt-5 flex gap-3"><input className="input max-w-24" type="number" min="1" max="10" value={qty} onChange={e => setQty(e.target.value)} /><button className="btn-navy" onClick={() => addToCart({ productId: p._id, qty })}>Add to Cart</button><button className="btn-gold" onClick={() => addToCart({ productId: p._id, qty })}>Buy Now</button><button className="rounded-lg border px-4 text-navy" onClick={() => wish(p._id)}><FaHeart /></button></div><div className="mt-8"><div className="flex flex-wrap gap-2">{['Description','Nutrition Facts','How to Use','Reviews'].map(t => <button className={`rounded px-4 py-2 ${tab===t?'bg-navy text-white':'bg-gray-100 text-navy'}`} onClick={() => setTab(t)} key={t}>{t}</button>)}</div><div className="mt-4 rounded-lg border p-5 text-gray-700">{tab === 'Description' ? p.description : tab === 'Reviews' ? 'Star breakdown and customer reviews appear here after verified purchases.' : 'Premium product details for informed buying.'}</div></div></section></div></main>; }
